### ISSUE TITLE
[Enhancement] French Language Pack

### ISSUE THREAD

**Issue by vlec-be** [gerardnico/dokuwiki-plugin-404manager#4]
See https://github.com/gerardnico/dokuwiki-plugin-404manager/pull/3

**Comment by gerardnico** [comment]
J'ai deja eu un mail pour la demande de merge. Je viens de le merger. Merci beaucoup, nos amis francais apprecieront ;)

**Comment by vlec-be** [comment]
Tout à fait d'accord
