### ISSUE TITLE
Last Update date

### ISSUE THREAD

**Issue by vlec-be** [gerardnico/dokuwiki-plugin-404manager#5]
I saw that the plugin has no last update date. 
For the next update... you know what to do
Thank you! :-)

**Comment by gerardnico** [comment]
What do you mean with no last update date ?
Do I need to add a line in:
https://github.com/gerardnico/dokuwiki-plugin-404manager/blob/master/plugin.info.txt
There is already a date line.
See https://www.dokuwiki.org/devel:plugin_info

**Comment by vlec-be** [comment]
I mean on the wiki repository (dokuwiki.org/plugins) and in extension manager (search and download)

**Comment by gerardnico** [comment]
If I click on the "edit" button, I get to see;
lastupdate : 2015-11-3
Is it not good of do I need to do something ?

**Comment by vlec-be** [comment]
The problem is not in the plugin actually
Look on the Dokuwiki website : http://image.noelshack.com/fichiers/2016/12/1458751655-sans-titre-1.png

Looks the same when getting the plugin through Plugin manager.

**Comment by gerardnico** [comment]
Yo tricky, this was because the date number was 3 and not 03. I just changed it.

See commit : 17bb465b35e20e2ac874642bdfad7802f5ce3745

Thanks
