### ISSUE TITLE
Alert box not going away, even if existing URL is entered

### ISSUE THREAD

**Issue by hasinasi** [gerardnico/dokuwiki-plugin-404manager#6]
I just noticed the following problem: if I enter a non-existing URL, the plugin first works as expected: by showing an alert box and redirecting to an existing page. However, I noticed that the alert box never goes away, even if I enter an allowed URL.
I am still on "Elenor of Tsort", but I will upgrade to Frusterick Manners, soon. I can report back then.

**Comment by gerardnico** [comment]
Can I have a snapshot ?
What do you mean by an allowed URL ? An URL that have a page, that shows some content and you get still a redirection message ?

**Comment by gerardnico** [comment]
This error will be solved with the latest version. Dokuwiki had introduced a cache mechanism. The redirections will be now real redirections. I'm testing it on my website first and let you know.

**Comment by gerardnico** [comment]
Last version released with real redirections that close this issue
