### ISSUE TITLE
blank screen after last update

### ISSUE THREAD

**Issue by sabinich** [gerardnico/dokuwiki-plugin-404manager#8]
Hi, Gerard and everyone

When i trying update plugin to 2018-08-21 version on lastest dokuwiki, i have founding blank screen on any pages (excluding administration panel). And no one error into log-files.

**Comment by gerardnico** [comment]
I have run a test on the last one and it works.
https://travis-ci.org/gerardnico/dokuwiki-plugin-404manager/builds/452778395

This is related to the loading of Dokuwiki, it seems:
See:
https://github.com/splitbrain/dokuwiki/issues/2340

**Comment by gerardnico** [comment]
Creating the file `inc/Plugin.php` with this content works for me:

https://github.com/splitbrain/dokuwiki/blob/stable/inc/Plugin.php

Cheers
Nico
